version: '3.8'
services:
  my-sql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "abcde"
      MYSQL_DATABASE: blog-app
      MYSQL_USER: mysql
      MYSQL_PASSWORD: "abc"
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
  backend:
    depends_on:
      - my-sql
    build:
      dockerfile: dockerfile
      context: .
    environment:
      # ENABLE_PRISMA_LOG: false
      # SERVER_PORT: 3000
      DATABASE_URL: 'mysql://mysql:abc@my-sql:3306/blog-app'
    ports:
      - '8000:8000'
    volumes:
      - .:/app
volumes:
  mysql-data:
  node_modules: